services:
  hadoop-core:
    build:
      context: ./hadoop-core
      dockerfile: Dockerfile
    image: hadoop-core

  hadoop-master:
    build:
      context: ./master
      dockerfile: Dockerfile
    image: hadoop-master
    depends_on:
      - hadoop-core

  hadoop-slave:
    build:
      context: ./slave
      dockerfile: Dockerfile
    image: hadoop-slave
    depends_on:
      - hadoop-core