services:
  master:
    image: hadoop-master
    container_name: master
    hostname: tanhung-master

    ports:
      - "60070:50070"
      - "9004:9004"
      - "9870:9870"
      - "9864:9864"
      - "8042:8042"
      - "8088:8088"
    networks:
      - hadoop-net
    command: /bin/bash -c "service ssh start; tail -f /dev/null"
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./logs:/hadoop/logs
 
  slave1: 
    image: hadoop-slave
    container_name: slave1 
    hostname: tanhung-slave1 
    networks: 
      - hadoop-net 
    command: /bin/bash -c "service ssh start; tail -f /dev/null"
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
      - ./logs:/hadoop/logs

 
  slave2: 
    image: hadoop-slave
    container_name: slave2 
    hostname: tanhung-slave2 
    networks: 
      - hadoop-net 
    command: /bin/bash -c "service ssh start; tail -f /dev/null"
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
      - ./logs:/hadoop/logs

networks:
  hadoop-net:
    driver: bridge
